### ISSUE TITLE
Feature Request: Unified API for working with Handles

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [tesselode/kira#35]
Currently, static and streaming `SoundData::Handle`s have no unified API (e.g. if you are working with both types in the same context you must handle each as a seperate case.
It would be really nice if there was a seperate SoundHandle trait that both static and streaming sound handles implemented to that contained the methods they have in common.

(if something like this already exists, please point me towards it, I'm pretty new to Rust :))

**Comment by tesselode** [comment]
That would be nice; the problem is the `Sound` trait can be implemented by anyone, and there's no guarantee that those implementations will have any given features, like pausing, setting the volume, etc. It would be possible to make a handle just for static and streaming sound data, but for now I'd rather err on the side of Kira not including things that the user could relatively easily make themselves.
